spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5435/SZUP
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hibernate:
          schema_update:
            unique_constraint_strategy: RECREATE_QUIETLY
        format_sql: true
        default_schema: public

server:
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
  port: 8080
  error:
    include-stacktrace: never